src/Entity/Activity.php
<?php

namespace App\Entity;

use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActivityRepository::class)
 */
class Activity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_free;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $worker;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $places_total;

    /**
     * @ORM\Column(type="integer", options={"default" : 0}, nullable=true)
     */
    private $places_taken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $schedule;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\Column(type="boolean", options={"default" : 1}, nullable=true)
     */
    private $is_visible;

    /**
     * @ORM\Column(type="boolean", options={"default" : 0}, nullable=true)
     */
    private $is_deleted;

    /**
     * @ORM\ManyToOne(targetEntity=Entity::class, inversedBy="activities")
     * @ORM\JoinColumn(nullable=true)
     */
    private $entity;

    /**
     * @ORM\ManyToOne(targetEntity=AgeRange::class, inversedBy="activity")
     */
    private $ageRange;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="activity")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Ticket::class, mappedBy="activity", orphanRemoval=true)
     */
    private $tickets;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_morinig;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get the value of is_free
     */ 
    public function getIsFree()
    {
        return $this->is_free;
    }

    /**
     * Set the value of is_free
     *
     * @return  self
     */ 
    public function setIsFree($is_free)
    {
        $this->is_free = $is_free;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getWorker(): ?string
    {
        return $this->worker;
    }

    public function setWorker(?string $worker): self
    {
        $this->worker = $worker;

        return $this;
    }

        /**
     * Get the value of places_taken
     */ 
    public function getPlacesTaken()
    {
        return $this->places_taken;
    }

    /**
     * Set the value of places_taken
     *
     * @return  self
     */ 
    public function setPlacesTaken($places_taken)
    {
        $this->places_taken = $places_taken;

        return $this;
    }

    /**
     * Get the value of places_total
     */ 
    public function getPlacesTotal()
    {
        return $this->places_total;
    }

    /**
     * Set the value of places_total
     *
     * @return  self
     */ 
    public function setPlacesTotal($places_total)
    {
        $this->places_total = $places_total;

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->is_deleted;
    }

    public function setIsDeleted(bool $is_deleted): self
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    public function getEntity(): ?Entity
    {
        return $this->entity;
    }

    public function setEntity(?Entity $entity): self
    {
        $this->entity = $entity;

        return $this;
    }

    public function getAgeRange(): ?AgeRange
    {
        return $this->ageRange;
    }

    public function setAgeRange(?AgeRange $ageRange): self
    {
        $this->ageRange = $ageRange;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->setActivity($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getActivity() === $this) {
                $ticket->setActivity(null);
            }
        }

        return $this;
    }

    public function isIsMorinig(): ?bool
    {
        return $this->is_morinig;
    }

    public function setIsMorinig(?bool $is_morinig): self
    {
        $this->is_morinig = $is_morinig;

        return $this;
    }

    public function __toString() {
        return $this->entity;
    }

}

templates/includes/activity_list.html.twig
<table class="table table-striped table-hover text-center table-bordered my-2">
    <thead>
        <tr>
            <th class="px-3">Nom activitat</th>
            <th>Inici</th>
            <th>Fi</th>
            <th>Places</th>
            <th>Preu</th>
            <th>Accions</th>
        </tr>
    </thead>

      <tbody>

            {% if activities|length > 0 %}
                {% for activity in activities %}

                    <tr>                                 
                        <td class="text-start px-3"><a href="{{ path('activity_show', {'id': activity.id})}}">{{ activity.name }}</a></td>
                        <td class="col-1">{{ activity.startDate|date('d-m-Y') }}</td>
                        <td class="col-1">{{ activity.endDate|date('d-m-Y') }}</td>
                        <td class="disponibility">{{ activity.placesTaken }} / {{ activity.placesTotal }} </td>
                            {% if activity.isFree %}
                                <td>
                                    <img width="40" title="Activitat gratuïta" alt="Activitat gratuïta" src="{{ asset('/res/no-cost.png')}}">
                                </td>
                            {% else %}
                                <td class="p-2">
                                <img width="32" title="Activitat de pagament" alt="Activitat de pagament" src="{{ asset('/res/payment.png')}}">
                                </td>
                            {% endif %}
                        <td>
                        
                        <a href=" {{ path('activity_edit', {'id': activity.id}) }}"></a>

                        {# INICI EDITAR #}
                        <a href="{{ path('activity_edit', {'id': activity.id}) }}" type="button" class="btn btn-primary"  data-bs-toggle="tooltip" data-bs-placement="top" title="Editar">
                            <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                <path d="M384 224v184a40 40 0 01-40 40H104a40 40 0 01-40-40V168a40 40 0 0140-40h167.48" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="42" />
                                <path d="M459.94 53.25a16.06 16.06 0 00-23.22-.56L424.35 65a8 8 0 000 11.31l11.34 11.32a8 8 0 0011.34 0l12.06-12c6.1-6.09 6.67-16.01.85-22.38zM399.34 90L218.82 270.2a9 9 0 00-2.31 3.93L208.16 299a3.91 3.91 0 004.86 4.86l24.85-8.35a9 9 0 003.93-2.31L422 112.66a9 9 0 000-12.66l-9.95-10a9 9 0 00-12.71 0z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="15" />
                            </svg>
                        </a>
                        {# FI EDITAR #}

                        {# INICI ELIMINAR #}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalDelete{{activity.id}}" data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar">
                            <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                <path d="M112 112l20 320c.95 18.49 14.4 32 32 32h184c17.67 0 30.87-13.51 32-32l20-320" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M80 112h352" />
                                <path d="M192 112V72h0a23.93 23.93 0 0124-24h80a23.93 23.93 0 0124 24h0v40M256 176v224M184 176l8 224M328 176l-8 224" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                            </svg>
                        </button>
                        {# FI ELIMINAR #}

               
                        {# INICI OCULTAR #}
                        {% if activity.isVisible %}
                            <a type="button" class="btn btn-primary" href="{{ path('activity_toggle_visibility', {'id' : activity.id}) }}"  data-bs-toggle="tooltip" data-bs-placement="top" title="Ocultar">
                                <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                    <path d="M432 448a15.92 15.92 0 01-11.31-4.69l-352-352a16 16 0 0122.62-22.62l352 352A16 16 0 01432 448zM255.66 384c-41.49 0-81.5-12.28-118.92-36.5-34.07-22-64.74-53.51-88.7-91v-.08c19.94-28.57 41.78-52.73 65.24-72.21a2 2 0 00.14-2.94L93.5 161.38a2 2 0 00-2.71-.12c-24.92 21-48.05 46.76-69.08 76.92a31.92 31.92 0 00-.64 35.54c26.41 41.33 60.4 76.14 98.28 100.65C162 402 207.9 416 255.66 416a239.13 239.13 0 0075.8-12.58 2 2 0 00.77-3.31l-21.58-21.58a4 4 0 00-3.83-1 204.8 204.8 0 01-51.16 6.47zM490.84 238.6c-26.46-40.92-60.79-75.68-99.27-100.53C349 110.55 302 96 255.66 96a227.34 227.34 0 00-74.89 12.83 2 2 0 00-.75 3.31l21.55 21.55a4 4 0 003.88 1 192.82 192.82 0 0150.21-6.69c40.69 0 80.58 12.43 118.55 37 34.71 22.4 65.74 53.88 89.76 91a.13.13 0 010 .16 310.72 310.72 0 01-64.12 72.73 2 2 0 00-.15 2.95l19.9 19.89a2 2 0 002.7.13 343.49 343.49 0 0068.64-78.48 32.2 32.2 0 00-.1-34.78z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12" />
                                    <path d="M256 160a95.88 95.88 0 00-21.37 2.4 2 2 0 00-1 3.38l112.59 112.56a2 2 0 003.38-1A96 96 0 00256 160zM165.78 233.66a2 2 0 00-3.38 1 96 96 0 00115 115 2 2 0 001-3.38z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="10" />
                                </svg>
                            </a>
                        {% else %}
                            <a type="button" class="btn btn-secondary" href="{{ path('activity_toggle_visibility', {'id' : activity.id}) }}"  data-bs-toggle="tooltip" data-bs-placement="top" title="Mostrar">
                                <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                    <path d="M255.66 112c-77.94 0-157.89 45.11-220.83 135.33a16 16 0 00-.27 17.77C82.92 340.8 161.8 400 255.66 400c92.84 0 173.34-59.38 221.79-135.25a16.14 16.14 0 000-17.47C428.89 172.28 347.8 112 255.66 112z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/>
                                    <circle cx="256" cy="256" r="80" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/>
                                </svg>
                            </a>
                        {% endif %}
                        {# FI OCULTAR #}



                        {# INICI ESTADÍSTIQUES #}
                        {# <button type="button" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                <rect x="64" y="320" width="48" height="160" rx="8" ry="8" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <rect x="288" y="224" width="48" height="256" rx="8" ry="8" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <rect x="400" y="112" width="48" height="368" rx="8" ry="8" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <rect x="176" y="32" width="48" height="448" rx="8" ry="8" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                            </svg>
                        </button> #}
                        {# FI ESTADÍSTIQUES #}


                        {# INICI LLISTA PARTICIPANTS #}
                        {# <button type="button" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M160 144h288M160 256h288M160 368h288" />
                                <circle cx="80" cy="144" r="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <circle cx="80" cy="256" r="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <circle cx="80" cy="368" r="16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                            </svg>
                        </button> #}
                        {# FI LLISTA PARTICIPANTS #}

                        </td>
                    </tr>
                    <script>
                        var total = {{ activity.placesTotal }};
                        var taken = {{ activity.placesTaken }};
                    </script>

                    
                    <!-- Modal -->
                    <div class="modal fade" id="modalDelete{{activity.id}}" tabindex="-1" role="dialog" aria-labelledby="modalDeleteTitle{{activity.id}}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">{{ activity.name }}</h5>
                                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>            
                            </div>
                            <div class="modal-body">
                                Vols eliminar l'activitat?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    CANCELAR
                                </button>
                                <a type="button" class="btn special-btn" href="{{ path("activity_delete", {'id' : activity.id}) }}">
                                    ELIMINAR
                                </a>
                            </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="6">no hi ha activitats</td>
                </tr>
            {% endif %}

    </tbody> 
</table>

templates/includes/modal.html.twig
<!-- Modal -->
<div class="modal fade" id={{ id }} tabindex="-1" role="dialog" aria-labelledby="modalDeleteTitle{{activity.id}}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">{{ activity.name }}</h5>
            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>            
        </div>
        <div class="modal-body">
            Vols eliminar l'activitat?
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                CANCELAR
            </button>
            <button type="button" class="btn special-btn">
                ELIMINAR
            </button>
        </div>
        </div>
    </div>
</div>

templates/includes/ticket_list_activity.html.twig
<table class="table table-striped table-hover text-center table-bordered my-2">
    <thead>
        <tr>
            <th class="px-3">Nom</th>
            <th>Teléfon</th>
            <th>Estat tiquet</th>
            <th>Accions</th>
        </tr>
    </thead>

      <tbody>
            {% if tickets|length > 0 %}
                {% set i = 1 %}
                {% for ticket in tickets %}
                    {% set i = i + 1 %}
                    {% set participant = ticket.getParticipant() %}
                    {% set activity = ticket.getActivity() %}
                    {% set ticketStatus = ticket.getTicketStatus() %}

                    <tr>                                 
                        <td class="text-start px-3">{{ participant.name }}</td>
                        <td class="col-1">{{ participant.phone }}</td>
                       <td>{{ ticketStatus.getDescription }} </td>
                        <td>

                            {% if waiting is not defined %}   

                                {% if ticketStatus.id == 1 %}
                                    {# INICI ENVIAR A LA LLISTA #}
                                    <a href="{{ path('ticket_toggle_ticket_status', {'id': ticket.id}) }}" type="button" class="btn btn-primary"  data-bs-toggle="tooltip" data-bs-placement="top" title="Confirmar inscripció">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                            <rect x="64" y="64" width="384" height="384" rx="48" ry="48" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"></rect>
                                        </svg>
                                        <span>
                                            Confirmar inscripció
                                        </span>
                                    </a>
                                    {# FI ENVIAR A LA LLISTA #}
                                {% else %}
                                    {# INICI ENVIAR A LA LLISTA #}
                                    <a href="{{ path('ticket_toggle_ticket_status', {'id': ticket.id}) }}" type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M352 176L217.6 336 160 272"></path>
                                            <rect x="64" y="64" width="384" height="384" rx="48" ry="48" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"></rect>
                                        </svg>
                                        <span>
                                            Inscripció feta
                                        </span>
                                    </a>
                                    {# FI ENVIAR A LA LLISTA #}
                                {% endif %}


                                {# INICI ENVIAR A LA LLISTA #}
                                <a href="{{ path('ticket_toggle_waiting_list', {'id': ticket.id}) }}" type="button" class="btn btn-danger"  data-bs-toggle="tooltip" data-bs-placement="top" title="Enviar a llista d'espera">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M400 256H112"/>
                                    </svg>
                                    <span>
                                        Enviar a espera
                                    </span>
                                </a>
                                {# FI ENVIAR A LA LLISTA #}

                                
                            {% else %}   

                                {# INICI ENVIAR A LA LLISTA #}
                                <a href="{{ path('ticket_toggle_waiting_list', {'id': ticket.id}) }}" type="button" class="btn btn-primary"  data-bs-toggle="tooltip" data-bs-placement="top" title="Editar">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M256 112v288M400 256H112"/>
                                    </svg>
                                    <span>
                                        Afegir a la llista
                                    </span>
                                </a>
                                {# FI ENVIAR A LA LLISTA #}

                            {% endif %}   
                            
                        

                        </td>
                    </tr>

                    
                    <!-- Modal -->
                    <div class="modal fade" id="modalDelete{{participant.id}}" tabindex="-1" role="dialog" aria-labelledby="modalDeleteTitle{{participant.id}}" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">{{ participant.name }}</h5>
                                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>            
                            </div>
                            <div class="modal-body">
                                Vols eliminar aquest tiquet?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    CANCELAR
                                </button>
                                <a type="button" class="btn special-btn" href="{{ path("activity_remove_participant", {'id' : ticket.id}) }}">
                                    ELIMINAR
                                </a>
                            </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% else %}
                {% set i = 1 %}
            {% endif %}
            {% for iterator in i..activity.placesTotal %}

                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> 
                        <button type="button" class="btn btn-primary" data-toggle="modal" style="visibility:hidden">
                            <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                <path d="M112 112l20 320c.95 18.49 14.4 32 32 32h184c17.67 0 30.87-13.51 32-32l20-320" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M80 112h352" />
                                <path d="M192 112V72h0a23.93 23.93 0 0124-24h80a23.93 23.93 0 0124 24h0v40M256 176v224M184 176l8 224M328 176l-8 224" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                            </svg>
                        </button> 
                    </td>
                </tr>
                            
            {% endfor %}

    </tbody> 
</table>

templates/includes/ticket_list_participant.html.twig
<table class="table table-striped table-hover text-center table-bordered my-2">
    <thead>
        <tr>
            {# <th class="px-3">Centre</th> #}
            <th>Nom activitat</th>
            <th>Inici</th>
            <th>Fi</th>
            <th>Estat tiquet</th>
            <th>Accions</th>
        </tr>
    </thead>

    <tbody>

        {% if tickets|length > 0 %}
            {% for ticket in tickets %}

                {% set participant = ticket.getParticipant() %}
                {% set activity = ticket.getActivity() %}
                {% set ticketStatus = ticket.getTicketStatus() %}

                <tr>                                 
                    <td class="text-start px-3"><a href="{{ path('activity_show', {'id': activity.id})}}">{{ activity.name }}</a></td>
                    <td class="col-1">{{ activity.startDate|date('d/m/Y') }}</td>
                    <td class="col-1">{{ activity.endDate|date('d/m/Y') }} </td>
                    <td class="col-2">{{ ticketStatus.description }} </td>
                    
                    <td>
                        

                            {# INICI EDITAR #}
                            {# <a href="{{ path('activity_edit', {'id': participant.id}) }}" type="button" class="btn btn-primary data-bs-toggle="tooltip" data-bs-placement="top" title="Editar"">
                                <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                    <path d="M384 224v184a40 40 0 01-40 40H104a40 40 0 01-40-40V168a40 40 0 0140-40h167.48" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="42" />
                                    <path d="M459.94 53.25a16.06 16.06 0 00-23.22-.56L424.35 65a8 8 0 000 11.31l11.34 11.32a8 8 0 0011.34 0l12.06-12c6.1-6.09 6.67-16.01.85-22.38zM399.34 90L218.82 270.2a9 9 0 00-2.31 3.93L208.16 299a3.91 3.91 0 004.86 4.86l24.85-8.35a9 9 0 003.93-2.31L422 112.66a9 9 0 000-12.66l-9.95-10a9 9 0 00-12.71 0z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="15" />
                                </svg>
                            </a> #}
                            {# FI EDITAR #}

                            {# INICI ELIMINAR #}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalDelete{{ticket.id}}" data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar">
                                <svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">
                                    <path d="M112 112l20 320c.95 18.49 14.4 32 32 32h184c17.67 0 30.87-13.51 32-32l20-320" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                    <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M80 112h352" />
                                    <path d="M192 112V72h0a23.93 23.93 0 0124-24h80a23.93 23.93 0 0124 24h0v40M256 176v224M184 176l8 224M328 176l-8 224" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" />
                                </svg>
                            </button>
                            {# FI ELIMINAR #}


                    </td>
                </tr>

                
                <!-- Modal -->
                <div class="modal fade" id="modalDelete{{ticket.id}}" tabindex="-1" role="dialog" aria-labelledby="modalDeleteTitle{{ticket.id}}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">{{ ticket.getActivity.name }}</h5>
                            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>            
                        </div>
                        <div class="modal-body">
                            Vols eliminar aquest tiquet i la seva informació associada?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                CANCELAR
                            </button>
                            <a type="button" class="btn special-btn" href="{{ path("ticket_delete", {'id' : ticket.id}) }}">
                                ELIMINAR
                            </a>
                        </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6">no hi ha tickets</td>
            </tr>
        {% endif %}

    </tbody> 
</table>